language: node_js
node_js:
 — “20”
branches:
 only:
 — main
 - PROD
before_script:
 — npm install -g ionic
 — npm ci
script:
 — ionic build --prod -- --base-href ./
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 keep-history: true
 on:
   branch: main
 local_dir: www
