dist: jammy
language: node_js
node_js:
  - "20.11.0"
os:
  - linux
branches:
  only:
    - main
    - PROD
before_script:
  - npm i -g npm@10.2.4
  - npm install -g @angular/cli
  - npm install -g ionic
  - npm ci
  - export display=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint
  # - npm run test -- --watch=false
  - ionic build --prod -- --base-href ./
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 keep-history: true
 on:
   branch: main
 local_dir: www
